name: Time Workflow

on:
  push:
    branches: [ main ]  # Triggers automatically on push to the main branch for immediate execution

jobs:
  send-time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get current time and send to Telegram
        run: |
          CURRENT_TIME_UTC=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          CURRENT_TIME_LOCAL=$(date +"%Y-%m-%d %H:%M:%S %Z")
          
          MESSAGE="Current UTC time: ${CURRENT_TIME_UTC}\nCurrent local time: ${CURRENT_TIME_LOCAL}"

